
ABLATION_GAME = "ablation"
SET_ABLATION_GAME = "set_ablation"

DS_TUNABILITY_GAME = "data_specific_tunability"
TUNABILITY_GAME = "tunability"

DS_OPTIMIZER_BIAS_GAME = "data_specific_optimizer_bias"
OPTIMIZER_BIAS_GAME = "optimizer_bias"

OB_GAME_SET_A_SUFFIX = "-set-a"
OB_GAME_SET_B_SUFFIX = "-set-b"

COMPLETE_GAME_LIST = [
    ABLATION_GAME,
    SET_ABLATION_GAME,
    DS_TUNABILITY_GAME,
    TUNABILITY_GAME,
    DS_OPTIMIZER_BIAS_GAME,
    OPTIMIZER_BIAS_GAME,
    OPTIMIZER_BIAS_GAME+OB_GAME_SET_A_SUFFIX,
    OPTIMIZER_BIAS_GAME+OB_GAME_SET_B_SUFFIX
]